---
# Setup base client for xray

- hosts: all

  tasks:

  - name: Set SAN Policy to OnlineAll
    win_shell: |
        Set-StorageSetting -NewDiskPolicy OnlineAll

  - name: Disable Windows Firewall
    win_command: netsh advfirewall set allprofiles state off

  - name: Installation of chocolatey, ssh and packages
    win_shell: |
        Set-ExecutionPolicy Bypass -Force
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install -y openssh -params "/SSHServerFeature" wget curl iperf3
        Import-Module C:\\ProgramData\\chocolatey\\helpers\\chocolateyProfile.psm1
        RefreshEnv

  - name: Create windows_exporter service with custom build in C:\
    win_shell: |
        New-Service -BinaryPathName C:\windows_exporter.exe -DisplayName windows_exporter -Name windows_exporter -StartupType Automatic
        Start-Service windows_exporter

  - name: Disable password complexity requirements
    win_shell: |        
        secedit /export /cfg c:\secedit.cfg
        (gc c:\secedit.cfg) -Replace('PasswordComplexity = 1', 'PasswordComplexity = 0') | Out-File -Encoding ascii c:\secedit.cfg
        secedit /configure /db $env:windir\security\secedit.sdb /cfg c:\secedit.cfg /areas SECURITYPOLICY
        del c:\secedit.cfg

  - name: Set password policy to allow no expiration globally and for administrator account
    win_shell: |
        wmic useraccount WHERE Name='administrator' set PasswordExpires=false
        net accounts /MaxPWAge:unlimited

  - name: Create nutanix user and add to Administrators local group
    win_shell: |
        $Password = ConvertTo-SecureString "nutanix/4u" -AsPlainText -Force
        New-LocalUser -AccountNeverExpires -Password $Password -PasswordNeverExpires -Name "nutanix"
        Add-LocalGroupMember -Group Administrators -Member nutanix

  - name: Install fio using msi from GitHub
    win_shell: |
        wget https://github.com/axboe/fio/releases/download/fio-3.35/fio-3.35-x64.msi -OutFile c:\\fio-3.35-x64.msi
        msiexec /quiet /i fio-3.35-x64.msi
        Set-Item env:\Path -Value ($env:Path + ";C:\Program Files\fio")
        del c:\\fio-3.35-x64.msi
        echo "install done"