---
# Setup base client for xray

- hosts: all

  tasks:

  - name: Set SAN Policy to OnlineAll
    win_shell: |
        Set-StorageSetting -NewDiskPolicy OnlineAll

  - name: Disable Windows Firewall
    win_command: netsh advfirewall set allprofiles state off

  - name: Installation of chocolatey, ssh and packages
    win_shell: |
        Set-ExecutionPolicy Bypass -Force
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install -y openssh -params "/SSHServerFeature" wget curl iperf3 7zip
        Import-Module C:\\ProgramData\\chocolatey\\helpers\\chocolateyProfile.psm1
        RefreshEnv

  - name: Disable password complexity requirements
    win_shell: |        
        secedit /export /cfg c:\secedit.cfg
        (gc c:\secedit.cfg) -Replace('PasswordComplexity = 1', 'PasswordComplexity = 0') | Out-File -Encoding ascii c:\secedit.cfg
        secedit /configure /db $env:windir\security\secedit.sdb /cfg c:\secedit.cfg /areas SECURITYPOLICY
        del c:\secedit.cfg

  - name: Set password policy to allow no expiration globally and for administrator account
    win_shell: |
        wmic useraccount WHERE Name='administrator' set PasswordExpires=false
        net accounts /MaxPWAge:unlimited

  - name: Create nutanix user and add to Administrators local group
    win_shell: |
        $Password = ConvertTo-SecureString "nutanix/4u" -AsPlainText -Force
        New-LocalUser -AccountNeverExpires -Password $Password -PasswordNeverExpires -Name "nutanix"
        Add-LocalGroupMember -Group Administrators -Member nutanix

  - name: Install windows_exporter
    ansible.windows.win_package:
      path: https://github.com/prometheus-community/windows_exporter/releases/download/v0.24.0/windows_exporter-0.24.0-amd64.msi
      product_id: {FAF8BA71-6B12-4EC1-A5DF-A5C33008D7FE}
      state: present
      arguments: /qn /norestart

  - name: Install fio
    ansible.windows.win_package:
      path: https://github.com/axboe/fio/releases/download/fio-3.35/fio-3.35-x64.msi
      product_id: {B7EB2E35-942A-4373-BA92-3B2F0FA760C7}
      state: present
      arguments: /qn /norestart

  - name: Add fio to PATH
    ansible.windows.win_path:
      elements:
      - C:\Program Files\fio

  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot: