---
# Setup base client for xray

- hosts: all

  tasks:

  - name: Set SAN Policy to OnlineAll
    win_shell: |
        Set-StorageSetting -NewDiskPolicy OnlineAll

  - name: Install chocolatey, openssh wget fio 7zip prometheus-windows-exporter.install procexp procmon
    win_shell: |
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install -y openssh -params "/SSHServerFeature" wget fio 7zip procexp procmon
#        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\windows_exporter" -Name "ImagePath" `
#        -Value '"C:\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182 --collectors.enabled="cpu,net,physical_disk" --log.level=debug --collector.physical_disk.disk-blacklist=". C:"'
#        Restart-Service windows_exporter

  - name: Create root user and set password policy to allow no expiration globally and for administrator account
    win_shell: |
        wmic useraccount WHERE Name='administrator' set PasswordExpires=false
        net accounts /MaxPWAge:unlimited

	# disable password complexity requirements
	secedit /export /cfg c:\new.cfg
	${c:new.cfg}=${c:new.cfg} | % {$_.Replace('PasswordComplexity=1', 'PasswordComplexity=0')}
	secedit /configure /db $env:windir\security\new.sdb /cfg c:\new.cfg /areas SECURITYPOLICY
	del c:\new.cfg

	# create nutanix user and add to Administrators local group
	$Password = ConvertTo-SecureString "nutanix/4u" -AsPlainText -Force
	New-LocalUser -AccountNeverExpires -Password $Password -PasswordNeverExpires -Name "nutanix"
	Add-LocalGroupMember -Group Administrators -Member nutanix

  - name: RefreshEnv
    win_command: C:\ProgramData\chocolatey\bin\RefreshEnv.cmd

  - name: Disable Windows Firewall
    win_command: netsh advfirewall set allprofiles state off
